if(NOT DEFINED INPUT_VERSION_FILE OR NOT DEFINED OUTPUT_RC_FILE)
  message(FATAL_ERROR "INPUT_VERSION_FILE and OUTPUT_RC_FILE are required")
endif()
include("${INPUT_VERSION_FILE}")
if(NOT WINMCBOPOMOFO_VERSION_CORE MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
  message(FATAL_ERROR "Version core must be MAJOR.MINOR.PATCH without leading zeros")
endif()
set(VERSION_MAJOR "${CMAKE_MATCH_1}")
set(VERSION_MINOR "${CMAKE_MATCH_2}")
if(NOT WINMCBOPOMOFO_WINDOWS_REVISION MATCHES "^[1-9][0-9]*$" OR
   WINMCBOPOMOFO_WINDOWS_REVISION GREATER 65535 OR
   VERSION_MAJOR GREATER 255 OR VERSION_MINOR GREATER 255)
  message(FATAL_ERROR "Version exceeds Windows Installer limits or has invalid revision")
endif()
set(VERSION_STRING "${WINMCBOPOMOFO_VERSION_CORE}")
set(VERSION_FLAGS "0x0L")
if(NOT "${WINMCBOPOMOFO_VERSION_PRERELEASE}" STREQUAL "")
  if(NOT WINMCBOPOMOFO_VERSION_PRERELEASE MATCHES "^(alpha|beta|rc)\\.[1-9][0-9]*$")
    message(FATAL_ERROR "Prerelease must be alpha.N, beta.N, rc.N, or empty")
  endif()
  string(APPEND VERSION_STRING "-${WINMCBOPOMOFO_VERSION_PRERELEASE}")
  set(VERSION_FLAGS "0x2L")
endif()
set(MSI_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${WINMCBOPOMOFO_WINDOWS_REVISION}")
set(VERSION_COMMA "${VERSION_MAJOR},${VERSION_MINOR},${WINMCBOPOMOFO_WINDOWS_REVISION},0")
get_filename_component(OUTPUT_DIR "${OUTPUT_RC_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT_RC_FILE}"
  "#pragma once\n"
  "#define WINMCBOPOMOFO_VERSION_NUM ${VERSION_COMMA}\n"
  "#define WINMCBOPOMOFO_VERSION_STR \"${VERSION_STRING}\"\n"
  "#define WINMCBOPOMOFO_VERSION_FLAGS ${VERSION_FLAGS}\n")
if(DEFINED OUTPUT_METADATA_FILE)
  get_filename_component(METADATA_DIR "${OUTPUT_METADATA_FILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${METADATA_DIR}")
  file(WRITE "${OUTPUT_METADATA_FILE}"
    "{\"version\":\"${VERSION_STRING}\",\"msiVersion\":\"${MSI_VERSION}\"}\n")
endif()
message(STATUS "Release ${VERSION_STRING}; Windows Installer ${MSI_VERSION}")
